### PR TITLE
Downgrade instance

### PR DESCRIPTION
**Pull request by juliocc**

### CODE REVIEW

**Comment by atlantis700** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform plan -input=false -refresh -no-color -out \"/home/jccb/.atlantis/repos/gecepe/atlantisdemo/10/default/default.tfplan\"" in "/home/jccb/.atlantis/repos/gecepe/atlantisdemo/10/default": exit status 1

Error: Error locking state: Error acquiring the state lock: writing "gs://tf-atlantis/terraform/state/default.tflock" failed: googleapi: Error 412: Precondition Failed, conditionNotMet
Lock Info:
  ID:        1572433084455457
  Path:      gs://tf-atlantis/terraform/state/default.tflock
  Operation: OperationTypeApply
  Who:       jccb@atlantis
  Version:   0.12.12
  Created:   2019-10-30 10:58:04.389304906 +0000 UTC
  Info:      


Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.



```
</details>

**Comment by juliocc** [comment]
atlantis plan

**Comment by atlantis700** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform plan -input=false -refresh -no-color -out \"/home/jccb/.atlantis/repos/gecepe/atlantisdemo/10/default/default.tfplan\"" in "/home/jccb/.atlantis/repos/gecepe/atlantisdemo/10/default": exit status 1

Error: Error locking state: Error acquiring the state lock: writing "gs://tf-atlantis/terraform/state/default.tflock" failed: googleapi: Error 412: Precondition Failed, conditionNotMet
Lock Info:
  ID:        1572433084455457
  Path:      gs://tf-atlantis/terraform/state/default.tflock
  Operation: OperationTypeApply
  Who:       jccb@atlantis
  Version:   0.12.12
  Created:   2019-10-30 10:58:04.389304906 +0000 UTC
  Info:      


Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.



```
</details>

**Comment by juliocc** [comment]
terraform plan

**Comment by atlantis700** [comment]
Did you mean to use `atlantis` instead of `terraform`?

**Comment by juliocc** [comment]
atlantis plan

**Comment by atlantis700** [comment]
Ran Plan for dir: `.` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://35.240.92.119:4141/lock?id=gecepe%252Fatlantisdemo%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by juliocc** [comment]
atlantis apply

**Comment by atlantis700** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

vm = {
  "ip" = "10.132.0.41"
  "name" = "my-first-atlantis-vm"
}

```

**Comment by atlantis700** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
